chore: test alternative commandé

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -51,7 +51,12 @@ jobs:
           git config user.name "${{ github.actor }}"
           git config user.email "${{ github.actor}}@users.noreply.github.com"
 
-          npx lerna version --conventional-commits --conventional-graduate --create-release github --yes
+          npx lerna version --conventional-commits --conventional-graduate --create-release github --yes || export LERNA_VERSION_ERROR=$?
+
+          if [ -n "$LERNA_VERSION_ERROR" ]; then
+            echo "Error in lerna version. Running alternative command."
+          fi
+
           npx lerna publish from-git --yes
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
